# Dataset Analysis

In [17]:
# Choose dataset to analyze
DATASET_NAME = "../data/1_eurostat_new_passenger_cars_by_type_of_motor_energy_and_engine_size.csv"

In [18]:
import pandas as pd

df = pd.read_csv(DATASET_NAME)

In [19]:
df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,mot_nrg,Motor energy,engine,...,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:ROAD_EQR_CARMOT(1.0),New passenger cars by type of motor energy and...,A,Annual,NR,Number,DIE,Diesel,CC1400-1999,...,AT,Austria,1999,NaN,146817.0,NaN,d,definition differs (see metadata),NaN,NaN
1,dataflow,ESTAT:ROAD_EQR_CARMOT(1.0),New passenger cars by type of motor energy and...,A,Annual,NR,Number,DIE,Diesel,CC1400-1999,...,AT,Austria,2000,NaN,155684.0,NaN,d,definition differs (see metadata),NaN,NaN
2,dataflow,ESTAT:ROAD_EQR_CARMOT(1.0),New passenger cars by type of motor energy and...,A,Annual,NR,Number,DIE,Diesel,CC1400-1999,...,AT,Austria,2001,NaN,158020.0,NaN,d,definition differs (see metadata),NaN,NaN
3,dataflow,ESTAT:ROAD_EQR_CARMOT(1.0),New passenger cars by type of motor energy and...,A,Annual,NR,Number,DIE,Diesel,CC1400-1999,...,AT,Austria,2002,NaN,158103.0,NaN,d,definition differs (see metadata),NaN,NaN
4,dataflow,ESTAT:ROAD_EQR_CARMOT(1.0),New passenger cars by type of motor energy and...,A,Annual,NR,Number,DIE,Diesel,CC1400-1999,...,AT,Austria,2003,NaN,175893.0,NaN,NaN,NaN,NaN,NaN

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6422 entries, 0 to 6421
Data columns (total 21 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   STRUCTURE                               6422 non-null   object
 1   STRUCTURE_ID                            6422 non-null   object
 2   STRUCTURE_NAME                          6422 non-null   object
 3   freq                                    6422 non-null   object
 4   Time frequency                          6422 non-null   object
 5   unit                                    6422 non-null   object
 6   Unit of measure                         6422 non-null   object
 7   mot_nrg                                 6422 non-null   object
 8   Motor energy                            6422 non-null   object
 9   engine                                  6422 non-null   object
 10  Engine capacity of vehicle              6422 non-null   object
 11  geo                                     6422 non-null   object
 12  Geopolitical entity (reporting)         6422 non-null   object
 13  TIME_PERIOD                             6422 non-null   int64
 14  Time                                    0 non-null      float64
 15  OBS_VALUE                               6406 non-null   float64
 16  Observation value                       0 non-null      float64
 17  OBS_FLAG                                584 non-null    object
 18  Observation status (Flag) V2 structure  584 non-null    object
 19  CONF_STATUS                             16 non-null     object
 20  Confidentiality status (flag)           16 non-null     object
dtypes: float64(3), int64(1), object(17)
memory usage: 1.0+ MB

In [21]:
for col in df.columns:
    print(f"Column {col}: {df[col].unique()}")

Column STRUCTURE: ['dataflow']
Column STRUCTURE_ID: ['ESTAT:ROAD_EQR_CARMOT(1.0)']
Column STRUCTURE_NAME: ['New passenger cars by type of motor energy and engine size']
Column freq: ['A']
Column Time frequency: ['Annual']
Column unit: ['NR']
Column Unit of measure: ['Number']
Column mot_nrg: ['DIE' 'PET' 'TOTAL']
Column Motor energy: ['Diesel' 'Petrol' 'Total']
Column engine: ['CC1400-1999' 'CC_GE2000' 'CC_LT1400' 'TOTAL']
Column Engine capacity of vehicle: ['From 1 400 to 1 999 cm³' '2 000 cm³ or over' 'Less than 1 400 cm³'
 'Total']
Column geo: ['AT' 'BA' 'BE' 'CH' 'CY' 'CZ' 'DE' 'EE' 'EL' 'ES' 'FI' 'FR' 'GE' 'HR'
 'HU' 'IE' 'IS' 'IT' 'LI' 'LT' 'LU' 'LV' 'MD' 'ME' 'MT' 'NO' 'PL' 'PT'
 'RO' 'RS' 'SE' 'SI' 'TR' 'UA' 'UK' 'XK' 'AL' 'BG' 'DK' 'EU27_2020' 'NL'
 'SK' 'MK']
Column Geopolitical entity (reporting): ['Austria' 'Bosnia and Herzegovina' 'Belgium' 'Switzerland' 'Cyprus'
 'Czechia' 'Germany' 'Estonia' 'Greece' 'Spain' 'Finland' 'France'
 'Georgia' 'Croatia' 'Hungary' 'Ireland' 'Iceland' 'Italy' 'Liechtenstein'
 'Lithuania' 'Luxembourg' 'Latvia' 'Moldova' 'Montenegro' 'Malta' 'Norway'
 'Poland' 'Portugal' 'Romania' 'Serbia' 'Sweden' 'Slovenia' 'Türkiye'
 'Ukraine' 'United Kingdom' 'Kosovo*' 'Albania' 'Bulgaria' 'Denmark'
 'European Union - 27 countries (from 2020)' 'Netherlands' 'Slovakia'
 'North Macedonia']
Column TIME_PERIOD: [1999 2000 2001 2002 2003 2004 2006 2007 2008 2009 2010 2011 2012 2013
 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2005 1996 1997
 1998 1995 1992 1993 1994 1989 1990 1991 1979 1980 1981 1982 1983 1984
 1985 1986 1987 1988 1970 1975]
Column Time: [nan]
Column OBS_VALUE: [146817. 155684. 158020. ...  19500.   9842.  27171.]
Column Observation value: [nan]
Column OBS_FLAG: ['d' nan 'e' 'b' 'i' 'u' 'p']
Column Observation status (Flag) V2 structure: ['definition differs (see metadata)' nan 'estimated'
 'break in time series'
 'value imputed by Eurostat or other receiving agencies' 'low reliability'
 'provisional']
Column CONF_STATUS: [nan 'C']
Column Confidentiality status (flag): [nan 'confidential']

In [22]:
df["TIME_PERIOD"].min(), df["TIME_PERIOD"].max()

(np.int64(1970), np.int64(2024))

In [23]:
df["geo"].nunique(), df["Geopolitical entity (reporting)"].unique()

(43,
 array(['Austria', 'Bosnia and Herzegovina', 'Belgium', 'Switzerland',
        'Cyprus', 'Czechia', 'Germany', 'Estonia', 'Greece', 'Spain',
        'Finland', 'France', 'Georgia', 'Croatia', 'Hungary', 'Ireland',
        'Iceland', 'Italy', 'Liechtenstein', 'Lithuania', 'Luxembourg',
        'Latvia', 'Moldova', 'Montenegro', 'Malta', 'Norway', 'Poland',
        'Portugal', 'Romania', 'Serbia', 'Sweden', 'Slovenia', 'Türkiye',
        'Ukraine', 'United Kingdom', 'Kosovo*', 'Albania', 'Bulgaria',
        'Denmark', 'European Union - 27 countries (from 2020)',
        'Netherlands', 'Slovakia', 'North Macedonia'], dtype=object))

In [24]:
# Map unique geo to continent
import country_converter as coco

df_continent = pd.DataFrame({
    "geo": df["geo"].drop_duplicates()
})

# Remove 'EU27_2020' entry from the list of unique geo values
df_continent = df_continent[df_continent["geo"] != "EU27_2020"]

df_continent["continent"] = coco.convert(
    names=df_continent["geo"],
    to="continent",
    not_found="Unknown"
)

df_continent

     geo continent
0     AT    Europe
25    BA    Europe
37    BE    Europe
55    CH    Europe
76    CY      Asia
96    CZ    Europe
99    DE    Europe
120   EE    Europe
144   EL    Europe
151   ES    Europe
169   FI    Europe
197   FR    Europe
224   GE      Asia
232   HR    Europe
242   HU    Europe
265   IE    Europe
282   IS    Europe
290   IT    Europe
313   LI    Europe
334   LT    Europe
354   LU    Europe
366   LV    Europe
377   MD    Europe
388   ME    Europe
397   MT    Europe
419   NO    Europe
428   PL    Europe
438   PT    Europe
446   RO    Europe
461   RS    Europe
467   SE    Europe
487   SI    Europe
514   TR      Asia
528   UA    Europe
534   UK    Europe
555   XK    Europe
1657  AL    Europe
1736  BG    Europe
1850  DK    Europe
2306  NL    Europe
2481  SK    Europe
5984  MK    Europe

## Drop Unnecessary Columns

In [25]:
# Save in ../data/cleaned/ the new dataset with the columns dropped
df.drop(columns=['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency', 'unit', 'Unit of measure'], inplace=True)
df.to_csv('../data/cleaned/1c_eurostat_new_passenger_cars_by_type_of_motor_energy_and_engine_size.csv', index=False)

TODO: Rows with 'C' in CONF_STATUS need to be dropped or handled separately, as data may be missing for confidentiality reasons. Note this in the report.

TODO: Decide whether to drop non EU countries.